import io
import pandas as pd
import sqlite3
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
from reportlab.lib.enums import TA_LEFT
from reportlab.lib import colors

# Helper to get DB connection (reuse same function as in database.py)
def _get_connection():
    db_path = Path(__file__).parent / "database" / "diabetes.db"
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    return conn

def download_pdf(report_text: str, patient_id: str) -> bytes:
    """Generate a PDF containing the AI health report and basic patient details.
    Returns the PDF as a bytes object suitable for Streamlit download_button.
    """
    # Retrieve patient record for header info
    conn = _get_connection()
    cur = conn.cursor()
    cur.execute("SELECT name, age, gender, visit_date FROM patients WHERE patient_id = ?", (patient_id,))
    row = cur.fetchone()
    conn.close()
    name = row["name"] if row else ""
    age = row["age"] if row else ""
    gender = row["gender"] if row else ""
    visit_date = row["visit_date"] if row else ""

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=60, bottomMargin=40)
    styles = getSampleStyleSheet()
    styles["Normal"].fontName = "Helvetica"
    styles["Normal"].fontSize = 10
    styles["Heading1"].fontName = "Helvetica-Bold"
    styles["Heading1"].fontSize = 16
    elements = []

    # Header
    header = f"<b>DiabetesCare AI Health Report</b>"
    elements.append(Paragraph(header, styles["Heading1"]))
    elements.append(Spacer(1, 12))
    patient_info = f"<b>Patient ID:</b> {patient_id}<br/><b>Name:</b> {name}<br/><b>Age:</b> {age}<br/><b>Gender:</b> {gender}<br/><b>Visit Date:</b> {visit_date}"
    elements.append(Paragraph(patient_info, styles["Normal"]))
    elements.append(Spacer(1, 12))
    # Report body (already markdown, but ReportLab handles simple HTML)
    elements.append(Paragraph(report_text.replace("\n", "<br/>"), styles["Normal"]))
    # Footer
    elements.append(Spacer(1, 24))
    footer = "<font size=8 color=grey>Generated by DiabetesCare AI • Confidential</font>"
    elements.append(Paragraph(footer, styles["Normal"]))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

def download_csv(patient_id: str) -> bytes:
    """Export the full patient record (single row) as CSV bytes.
    Used for Streamlit download button.
    """
    conn = _get_connection()
    df = pd.read_sql_query("SELECT * FROM patients WHERE patient_id = ?", conn, params=(patient_id,))
    conn.close()
    csv_buffer = io.BytesIO()
    df.to_csv(csv_buffer, index=False)
    csv_bytes = csv_buffer.getvalue()
    csv_buffer.close()
    return csv_bytes
